# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Indigo"
email: central@indigoeditoraelivraria.com.br
description: "Dúvidas e respostas"
baseurl: "/faqindigo"
url: ""
color_theme:  "#FF7E00"
color_text:  "#fff"
language:  "en"

# Build settings
markdown: kramdown
permalink: /:categories/:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
