# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Indigo"
email: central@indigoeditoraelivraria.com.br
description: "Dúvidas e respostas"
baseurl: "/faqindigo"
url: "www.indigoeditoraelivraria.com.br"
color_theme:  "#FF7E00"
color_text:  "#fff"
language:  "pt-br"

# Build settings
markdown: kramdown
permalink: /:categories/:titles
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin

# Category
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
